my_app/urls.py
from django.urls import path, include
from . import views

app_name = 'my_app'

urlpatterns = [
    path('', views.index, name='index'),
    # path('', include("django.contrib.auth.urls")),
    path('ajax/', views.ajax, name='ajax'),


]

project7/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('my_app.urls')),
    path('sign_in/', include('story_9.urls')),
]

story_9/urls.py
from django.urls import path
from . import views

from django.contrib.auth import authenticate, login, logout

app_name = 'story_9'

urlpatterns = [
    path('login/', views.loginView, name='loginView'),
    path('register/', views.register, name ='register'),
    path('logout/', views.logoutView, name='logoutView'),
    
]

my_app/models.py
from django.db import models

# Create your models here.

story_9/models.py
from django.db import models

# Create your models here.

story_9/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
	email = forms.EmailField()

	class Meta:
		model = User
		fields = ["username", "email", "password1", "password2"]

my_app/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'story7.html')

def ajax(request) :
    return render(request, 'ajax.html')

story_9/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from . import forms

response = {}

# Create your views here.
def register(response):
    if response.method == 'POST':
        form = forms.RegisterForm(response.POST)
        if form.is_valid():
            form.save()
            return redirect("story_9:loginView")
    else:
	    form = forms.RegisterForm()

    return render(response, 'register.html', {"form":form})

def loginView(request):

    user = None
    if request.method == "POST":

        username_login = request.POST['username']
        password_login = request.POST['password']
		
        user = authenticate(request, username=username_login, password=password_login)

        if user is not None:
            login(request, user)
            request.session['username'] = username_login
            response['username'] = request.session['username']


            return redirect('my_app:index')
        else:            
            return redirect("story_9:loginView")
            
    return render(request, 'login.html', response)


def logoutView(request):
    if request.method == "POST":
        if request.POST["logout"] == "Submit":
            request.session.flush()
            logout(request)

        return redirect('my_app:index')	

    return render(request, 'logout.html')

my_app/templates/ajax.html
<DOCTYPE 5>
    {% load static %}
<html>    
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://fonts.googleapis.com/css?family=Titillium+Web&display=swap" rel="stylesheet">
        <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <title>Story 7 & 8 & 9</title>       
    </head>
    <style>
        body{
            padding-top:50px;
        }
        .coverBook{   
            filter: drop-shadow(10px 10px 5px);
        }
        .mytable{
            font-family: 'Titillium Web', sans-serif;
            font-size: 30px;
        }
        .tableContent{
            font-family: 'Roboto';
            font-size: 20px;
        }
        .myButton{
            font-family: 'Roboto';
            font-weight: 700;
            background-color: #f8f8f8;
            box-shadow: 0px 8px 15px rgba(0, 0, 0, 0.1);
            border-radius: 35px;
            transition: all 0.3s ease 0s;
            cursor: pointer;
            outline: none;
        }
        .myButton:hover{
            background-color: #fcfcfc;
            box-shadow: 0px 15px 20px rgba(130, 139, 136, 0.4);
            color: #000;
            transform: translateY(-7px);
        }
        .textArea{
            width: 500px;
            box-sizing: border-box;
            box-shadow: 0px 8px 15px rgba(0, 0, 0, 0.1);
        
            background-color: #f8f8f8;
            font-size: 16px;
            resize: none;
            border-radius: 35px;
        }
        .textArea::placeholder {  
            font-style: italic;
        }
        #konten{
            padding-top: 20px;

        }
        .homeButton{
            font-family: 'Roboto';
            font-size : 20px;
            font-weight: 900;
            background-color: #f8f8f8;
            box-shadow: 0px 8px 15px rgba(0, 0, 0, 0.1);
            border-radius: 35px;
            transition: all 0.3s ease 0s;
            cursor: pointer;
            outline: none;
            
        }
    
    </style>
    <body >
        <div class="text-center">
            <h1 style="font-family: 'roboto';">FIND YOUR BOOK HERE</h1>
            <input id="search" class="textArea"  placeholder="  Write the title here...">
            <button class="myButton" id="button" type="button">FIND</button>
            <div class="container" id="konten">
                    <table border="1" class="table table-striped">
                        <thead class="myTable text-center">
                        </thead>
                        <tbody class="text-center tableContent" id="results">
                            
                        </tbody>
                    
                    </table>

            </div>
            <form action="{% url 'my_app:index' %}">
                <button class="homeButton"  type="submit">&#8678; Back to Homepage</button>
             </form>
        </div>    
        


        
        
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="{% static 'js/ajaxSlide.js' %}" type="text/javascript"></script>
    </body>

my_app/templates/story7.html
<DOCTYPE 5>
{% load static %}
<html>    
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Poppins&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Titillium+Web&display=swap" rel="stylesheet">
        <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <title>Story 7 & 8 & 9</title>       
    </head>
    <style>
        body{
            margin: 0;
           
        }
        section{
            position: absolute;
            left: 0;
            width: 100%;
            height: 100vh;
            box-sizing: border-box;
            
            background: url('/static/images/day.jpg') no-repeat center center fixed;
            background-size: cover;
            transition:0.5s;
            
        }
        section.dark {
            background: url('/static/images/night.jpg') no-repeat center center fixed;
            background-size: cover;
            color: #fff;

        }
        ul.tema{
            position: relative;
            margin-right: auto;
            margin-left: auto; 
            padding:0;
            width: 200px;
            height: 30px;
            z-index: 1;
            border: 1px solid #262626; 
            letter-spacing: 2.5px;
            transition: all 0.3s ease 0s;
            cursor: pointer;
            overflow: hidden;
            color: #262626;
        }
        ul.tema:hover{
            transform: translateY(7px);
            
        } 
        ul.tema.active {
            border-color: #fff;
        }
        ul.tema.active:hover{
            transform: translateY(7px);
            
        } 
        ul.tema li{
            list-style: none;
            width: 100%;
            height: 60px;
            text-align: center;
            text-transform: uppercase;
            transition: 0.5s;
            font-family: 'Titillium Web', sans-serif;
            font-size :25px
        }
        ul.tema.active li{
            transform: translateY(-30px);

        }
        ul.tema li span{
            display: block;
            height: 30px;
            line-height: 30px;
            width: 100%;
            color: #fff;
            background-color: transparent;
        }
        ul.tema li span:nth-child(1){
          color: #262626;  
        }
        .ihsan{
            padding-top: 75px;
            width: 200;
            height: auto;   
            filter: drop-shadow(10px 10px 5px);
        }
        .hello{
            font-family: 'Titillium Web', sans-serif;
            font-weight: normal;
            font-style: italic;
            font-size: 23px;
            padding-top: 15px;
        }
        .jquery_accordion_item {
            display: inline-block;
            width: 100%;
            border-bottom: 1px solid ;   
        }
        .jquery_accordion_title {
            text-decoration: underline;
            display: block;
            line-height: 140%;
            padding: 6px 40px 8px 8px;
            position: relative;
            cursor: pointer;
        }
        .jquery_accordion_title:after {
            content: "";
            width: 0;
            height: 0;
            display: inline-block;
            position: absolute;
            right: 15px;
            top: 50%;
            border: 6px solid transparent;
            border-top-color: #333;
            transition: border 400ms, margin 400ms;
            margin-top: -3px; /* half of border value */
        }
        .jquery_accordion_item.active .jquery_accordion_title:after {
            border-color: transparent;
            border-bottom-color: #333;
            margin-top: -9px; /* fixing arrow position */
        }
        .jquery_accordion_content {
            padding: 8px;
            display: none;
            border : 1px solid ;
            border-bottom: none;
            
        }
        .jquery_accordion_content > *:first-child {
            margin-top: 0;
        }
        .center{
            padding-top: 70px;
        }
        .accordion{
            font-family: 'Titillium Web', sans-serif;
            font-weight: normal;
            font-size: 23px;
        }
        .content{
            font-family: 'Poppins', sans-serif;
            font-size: 16px;
        }
        .more{
            font-family: 'Poppins', sans-serif;
            font-weight: lighter;
            font-size: 30px;
        }
        .libButton{
            font-family: 'Titillium Web', sans-serif;
            font-size : 20px;
            font-weight: bolder;
            background-color: transparent;
            border-radius: 35px;
            box-shadow: 0px 8px 15px rgba(0, 0, 0, 0.1);
            cursor: pointer;
            outline: none;     
            color: inherit;
        }
        .dropbtn {
            background: white;
            color: inherit;
            padding: 14px;
            font-size: 16px;
            font-family: 'Titillium Web', sans-serif;
            font-weight: 700;
            width:100%;

            
            border: thin solid #888;
            cursor: pointer;
            border-radius: 5px;
            box-shadow: 1px 1px 1px grey;
            letter-spacing: 0.5px;
             
        } 
        .dropdown {
            position: relative;
            display: inline-block;
            padding: 14px;
            
        }

        .dropdown-content {
            display: none;
            position: absolute;
            background-color: inherit;
            min-width: 128px;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
            z-index: 1;
        }

        .dropdown-content a {
            color: inherit;
            padding: 12px 16px;
            text-decoration: none;
            display: block;
        }

        .dropdown-content a:hover {background-color: #387fa8}

        .dropdown:hover .dropdown-content {
            display: block;
        }

        .dropdown:hover .dropbtn {
            background-color: #387fa8;
        } 
        .navbar-custom{
            background-color: transparent !important;
            
            position:static;
        }
        .users{
            color: inherit !important;
        }
        
    
    </style>
    <body>    
        <section>
            <nav class="navbar navbar-expand-md  navbar-dark sticky-top py-0 navbar-custom">
        <a class="navbar-brand" style="font-family:'Titillium Web', sans-serif; font-weight: 900; border: solid 1px; padding: 10px; border-radius: 25px ; color: whitesmoke;">Ihsan's</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'my_app:index' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'my_app:ajax' %}">Library</a>
            </li> 
            </ul>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle users" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="fas fa-user"></span>&nbsp;&nbsp;{{user.username}}</a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'story_9:loginView' %}"><span class="fas fa-sign-in-alt"></span>&nbsp;&nbsp;Log-in</a>
                        <a class="dropdown-item" href="{% url 'story_9:logoutView' %}"><span class="fas fa-sign-out-alt"></span>&nbsp;&nbsp;Log-out</a>
                    </div>
            </li>


        </div>  
        </nav>
    
            <div class="container-fluid" >
                <div class="row">
                    <div class="col">
                        <img class="mx-auto d-block ihsan" src="{% static 'images/ihsan5.PNG' %}">
                        <p class="text-center hello">"Hello {{user.username}}, welcome to my website."</p>
                        
                    </div>
                    <div class="col center">
                        <p class="more">&#9679; More about me &#9679;</p>
                        <div class="jquery_accordion_wrapper">
                            <div class="jquery_accordion_item">
                                <div class="jquery_accordion_title accordion" id="education">Education</div>
                                <div class="jquery_accordion_content content" >
                                    <p>- Al-Khairaat Islamic Elementary School</p>
                                    <p>- Buahati Islamic Junior High School</p>
                                    <p>- Senior High School 14 Jakarta</p>
                                    <p>- Computer Science, Universitas Indonesia</p>
                                </div>
                            </div>

                            <div class="jquery_accordion_item">
                                <div class="jquery_accordion_title accordion" id="organization">Organizational Experience</div>
                                <div class="jquery_accordion_content content" >
                                    <p>- IT-Tech 14 Senior High School</p>
                                    <p>- FUKI Fasilkom UI</p>
                                </div>
                            </div>

                            <div class="jquery_accordion_item">
                                <div class="jquery_accordion_title accordion" id="committe">Committe Experience</div>
                                <div class="jquery_accordion_content content" >
                                    <p>- Scooter (SHS 14 Cup)</p>
                                    <p>- Olimpiade UI 2018</p>
                                    <p>- Compfest XI</p>
                                    <p>- SIWAK-NG 2019</p>
                                </div>
                            </div>
                        </div>
                        <br>
                        <form action="{% url 'my_app:ajax' %}">
                                <button class="libButton"  type="submit">&#8680; Go to Library</button>
                        </form>
                    </div>
                </div>
            </div>
           
        </section>
        <ul class="text-center tema">
            <li>
                <span>Night</span>
                <span>Day</span>
            </li>
        </ul>
        
        
        <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
        <script src="{% static 'js/theme.js' %}" type="text/javascript"></script>
        <script src="{% static 'js/accordion.js' %}" type="text/javascript"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    </body>
</html>

story_9/templates/login.html
<DOCTYPE 5>
{% load static %}
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width =device-width">
  <title>Story 7 & 8 & 9</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


</head>
<style>
    * {
    box-sizing: border-box;
    font: Century;
    font-weight: 300;

    }

    html, body{
    height: 100%;

    }
    
    a {
        text-decoration: none;
        color: inherit;
    }

    ul .inside{
        overflow: hidden;
        display: none;
        list-style-type: disc;
    }

    .child {
        list-style-type: none;
    }



    li a.panels {
        margin: .5em 0;
        width: 100%;
        display: block;
        background: #181818;
        color: #fefefe;
        padding: .75em;
        border-radius: 0.15em;
        transition: background .3s ease;
        text-decoration: none;
    }

    .acc-list a:hover {
        text-decoration: none;
        margin: .5em 0;
        background: #ffbf00;
        color: black;
    }

    @import "compass/css3";
    *, *:before, *:after {
        box-sizing: border-box;
    }

    html {
        overflow-y: scroll;
    }

    body {
        background: #c1bdba;
        font-family: 'Titillium Web', sans-serif;
    }
    .background{
        background-color: whitesmoke;
  
    }


    a {
        text-decoration: none;
        color: #1a86b1;
        transition: 0.5s ease;
    }

    a:hover {
        color: #179b77;
    }

    .form {
        background: rgba(19, 35, 47, .9);
        padding: 40px;
        max-width: 600px;
        margin: 40px auto;
        border-radius: 4px;
        box-shadow: 0 4px 10px 4px rgba(19, 35, 47, .3);
        border-radius: 50px;
    }
    label {
        position: absolute;
        transform: translateY(6px);
        left: 13px;
        color: rgba(255, 255, 255, .5);
        transition: all 0.25s ease;
        -webkit-backface-visibility: hidden;
        pointer-events: none;
        font-size: 22px;
    }

    label .req {
        margin: 2px;
        color: #1a86b1;
    }

    label.active {
        transform: translateY(50px);
        left: 2px;
        font-size: 14px;
    }

    label.active .req {
        opacity: 0;
    }

    label.highlight {
        color: #fff;
    }

    .input, textarea {
        font-size: 22px;
        display: block;
        width: 500px;
        padding: 5px 10px;
        background: none;
        background-image: none;
        border: 1px solid #a0b3b0;
        color: #fff;
        border-radius: 0;
        transition: border-color 0.25s ease, box-shadow 0.25s ease;
    }

    .input:focus, textarea:focus {
        outline: 0;
        border-color: #1ab188;
    }

    .input, textarea {
        border: 2px solid #a0b3b0;
        resize: vertical;
    }

    .field-wrap {
        position: relative;
        margin-bottom: 40px;
    }

    .top-row:after {
        content: "";
        display: table;
        clear: both;
    }

    .top-row > div {
        float: left;
        width: 48%;
        margin-right: 4%;
    }

    .top-row > div:last-child {
        margin: 0;
    }

    .button {
        border: 0;
        outline: none;
        border-radius: 0;
        padding: 15px 0;
        font-size: 2rem;
        font-weight: 600;
        text-transform: uppercase;
        letter-spacing: 0.1em;
        background: #1a86b1;
        color: #fff;
        transition: all 0.5s ease;
        -webkit-appearance: none;
    }

    .button:hover, .button:focus {
        background: #179b77;
    }

    .button-block {
        display: block;
        width: 100%;
    }

    /* ------------------------------------ Click on login and Sign Up to  changue and view the effect
    ---------------------------------------
    */

</style>

<body class="background">

  <div class="form">
		

		<div class="tab-content">
			<div id="login">

				<form method="POST">
					{% csrf_token %}

					<div class="field-wrap">
						<label for="username">
						Username<span class="req">*</span>
						</label>
						<input class ="input" type="text" name="username" id="username_login" required autocomplete="off"/>
					</div>

					<div class="field-wrap">
						<label for="password">
						Password<span class="req">*</span>
						</label>
						<input class="input" type="password" name="password" id="password_login" required autocomplete="off"/>
					</div>

                    <button type="submit" id="submit_login" class="button button-block">Log In</button>
                    <p style="color:whitesmoke">Don't have an accoount? Create one <a href="{% url 'story_9:register' %}">here</a></p>

				</form>

			</div>

			<div ></div>

		</div><!-- tab-content -->

	</div> <!-- /form -->






<script src= "https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"> </script>


<script src = "{% static 'js/login.js' %}"></script>

<script src= "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"> </script>
<script src= "https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"> </script>
<script src= "https://use.fontawesome.com/releases/v5.0.8/js/all.js"> </script>


</body>


</html>

story_9/templates/logout.html
<DOCTYPE 5>
{% load static %}
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width =device-width">
  <title>Story 7 & 8 & 9</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


</head>
<style>
    * {
    box-sizing: border-box;
    font: Century;
    font-weight: 300;

    }

    html, body{
    height: 100%;

    }
    
  

    @import "compass/css3";
    *, *:before, *:after {
        box-sizing: border-box;
    }

    html {
        overflow-y: scroll;
    }

    body {
        background: #c1bdba;
        font-family: 'Titillium Web', sans-serif;
    }
    .background{
        background-color: whitesmoke;
  
    }


    a {
        text-decoration: none;
        color: #1a86b1;
        transition: 0.5s ease;
    }

    a:hover {
        color: #179b77;
    }

    .form {
        background: rgba(19, 35, 47, .9);
        padding: 40px;
        max-width: 600px;
        margin: 40px auto;
        border-radius: 4px;
        box-shadow: 0 4px 10px 4px rgba(19, 35, 47, .3);
        border-radius: 50px;
    }
   
    .button {
        border: 0;
        outline: none;
        border-radius: 0;
        padding: 15px 0;
        font-size: 2rem;
        font-weight: 600;
        text-transform: uppercase;
        letter-spacing: 0.1em;
        background: #1a86b1;
        color: #fff;
        transition: all 0.5s ease;
        -webkit-appearance: none;
    }

    .button:hover, .button:focus {
        background: #179b77;
    }

    .button-block {
        display: block;
        width: 100%;
    }

   

</style>

<body class="background">

  <div class="form">
		

		<div class="tab-content">
			<div id="login">

				<form method="POST">
					{% csrf_token %}
                    <input type="submit" name="logout" id="logout" class="button button-block">Log out</input>
                    
				</form>

			</div>

			<div ></div>

		</div><!-- tab-content -->

	</div> <!-- /form -->






<script src= "https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"> </script>


<script src = "{% static 'js/login.js' %}"></script>

<script src= "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"> </script>
<script src= "https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"> </script>
<script src= "https://use.fontawesome.com/releases/v5.0.8/js/all.js"> </script>


</body>


</html>

story_9/templates/register.html
<DOCTYPE 5>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Poppins&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Titillium+Web&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <title>Story 7 & 8 & 9</title>    
    </head>
    <body>
        {% load crispy_forms_tags %}

        {% block content %}
        <form method="POST" class="form-group">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Register</button>
        </form>
        {% endblock %}
    </body>
    
</html>